### PR TITLE
Haiku port

### PR DESCRIPTION
**Pull request by mmuman**
We don't have locale_t yet.

Some things should probably be tested by CMake instead of hardcoding ifdefs.

Some tests crash though.

We also have a native API for finding system directories.

### CODE REVIEW

**Comment by PanderMusubi** [comment]
@mmuman does Haiku have an online package search or similar sources? For now, I added the following to our wiki https://github.com/nuspell/nuspell/wiki/Nuspell-packaged-binaries#61-haiku

**Comment by dimztimz** [comment]
Hello @mmuman. At some point I'd like to switch to c++ 17 standardised filesystem facilities and drop the platform dependent code. I don't like to use configure time checks.

Also I'd drop the uselocale thing in favour of new c++17 number parsing functions that are always independent of locale.

Any changes should go towards that direction.

**Comment by mmuman** [comment]
> @mmuman does Haiku have an online package search or similar sources? 

Like https://depot.haiku-os.org/#!/?bcguid=bc1-ADTX&repos=clasqm,besly,fatelk,haikuports&arch=x86_gcc2&viewcrttyp=ALL&srchexpr=nuspell ?

**Comment by mmuman** [comment]
> Hello @mmuman. At some point I'd like to switch to c++ 17 standardised filesystem facilities and drop the platform dependent code. I don't like to use configure time checks.

Never used that, we're kind of old-fashioned in Haiku because we stick to the BeOS API…
So should I revert to the hardcoded `&& !defined(__HAIKU__)` instead for now?

**Comment by dimztimz** [comment]
For now I propose to use a minimal patch to get this compiling like your first commit, and then focus on those failed tests.

**Comment by mmuman** [comment]
Can you merge #43 so I can rebase on that one?

**Comment by mmuman** [comment]
As for the crash, it's inside an `std::string` destructor when calling `exit()`. I can reproduce by running nuspell directly with some input. If I just ctrl-d then it exits fine.

**Comment by dimztimz** [comment]
> Can you merge #43 so I can rebase on that one?

It is now.

> As for the crash, it's inside an `std::string` destructor when calling `exit()`. I can reproduce by running nuspell directly with some input. If I just ctrl-d then it exits fine.
> I created [an issue](https://github.com/haikuports/haikuports/issues/4718) in case someone else wants to help.

 I looked at that and it seems like Haiku has problems with thread-local storage.

**Comment by mmuman** [comment]
> > Can you merge #43 so I can rebase on that one?
> 
> It is now.

Ok just rebased.

> > As for the crash, it's inside an `std::string` destructor when calling `exit()`. I can reproduce by running nuspell directly with some input. If I just ctrl-d then it exits fine.
> > I created [an issue](https://github.com/haikuports/haikuports/issues/4718) in case someone else wants to help.
> 
> I looked at that and it seems like Haiku has problems with thread-local storage.

It's possible the recent C ABI support is missing something… we usually use our native TLS API so it's not really tested and we'll have to dig this.

**Comment by korli** [comment]
I'd like to mention that the issue https://github.com/haikuports/haikuports/issues/4718 is fixed and the Haiku patch is ATM this one:
https://github.com/haikuports/haikuports/blob/master/app-text/nuspell/patches/nuspell-4.2.0.patchset

**Comment by dimztimz** [comment]
Fixed.

**Comment by mmuman** [comment]
Thanks!

**Pull request closed without merging**
